version: 2.1
jobs:
  build:
    parameters:
      clojure-tag:
        type: string
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: /home/circleci/migratus
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-jars-{{ checksum "project.clj" }}
            - v1-dependency-jars
      - run: docker run --rm -u root -v $PWD:/root/migratus -v /var/run/docker.sock:/var/run/docker.sock -v $PWD/.m2:/root/.m2 -v $PWD/.lein:/root/.lein -w=/root/migratus cimg/clojure:<< parameters.clojure-tag >> lein test
      - store_test_results:
          path: /home/circleci/migratus/target
      - save_cache:
          key: v1-dependency-jars-{{ checksum "project.clj" }}
          paths:
            - /root/.m2
            - /root/.lein

workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              clojure-tag: ["1.10-openjdk-8.0", "1.11-openjdk-8.0", "1.11-openjdk-11.0", "1.11-openjdk-17.0"]
